### PR TITLE
tentatively solve warning 4 issues on is_ and _val functions

### PR DESCRIPTION
**Pull request by chrismamo1**
#11

### CODE REVIEW

**Comment by chrismamo1** [comment]
After this PR, the code:

```ocaml
type t =
  | A 
  | B 
  | C [@@deriving variants]
```

Emits the following `is_*` and `*_val` functions:

```ocaml
let is_a = function | A -> true | B | C -> false
let is_b = function | B -> true | A | C -> false
let is_c = function | C -> true | A | B -> false
let a_val =
  function | A -> Stdlib.Option.Some () | B | C -> Stdlib.Option.None
let b_val =
  function | B -> Stdlib.Option.Some () | A | C -> Stdlib.Option.None
let c_val =
  function | C -> Stdlib.Option.Some () | A | B -> Stdlib.Option.None
```

The generated code is a bit verbose, but it no longer triggers warning 4.

**Comment by chrismamo1** [comment]
After a bit more testing, I've realized that this fails on any variants encapsulating actual values. I'll look into this tomorrow.

**Comment by v-gb** [comment]
The problem with this approach is the bad compilation complexity: this generates a quadratic amount of code in the number of constructors (and types have sometimes many of these), and the pattern matching compilation is oftentimes quadratic even on patterns that could be clearly compiled in linear time, so this change would make compilation at least quadratic, and likely cubic.

That's why turning off the warning is better.

**Comment by chrismamo1** [comment]
That's very reasonable, I've adjusted the PR to simply add `[@@warning "-4"]` to each function that needs it.

**Comment by chrismamo1** [comment]
The code generated now looks more like this:

Source:
```ocaml
type t =
  | A
  | B of int
  | C
  [@@deriving variants]
```

Output:
```ocaml
let is_a = function | A -> true | _ -> false[@@warning "-4"]
let is_b = function | B _ -> true | _ -> false[@@warning "-4"]
let is_c = function | C -> true | _ -> false[@@warning "-4"]
let a_val =
  function | A -> Stdlib.Option.Some () | _ -> Stdlib.Option.None
  [@@warning "-4"]
let b_val =
  function | B v0 -> Stdlib.Option.Some v0 | _ -> Stdlib.Option.None
  [@@warning "-4"]
let c_val =
  function | C -> Stdlib.Option.Some () | _ -> Stdlib.Option.None
  [@@warning "-4"
```

**Comment by v-gb** [comment]
Looks good. I imported the change internally, it should be reflected here in perhaps a week.

**Pull request merged**
